version: "3.4"
services:
  NodeServiceContainerDef:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
      REGION: us-west-1
    image: brentley/ecsdemo-nodejs:cdk
    labels:
      ecs-local.task-definition-input.type: remote
      ecs-local.task-definition-input.value: arn:aws:ecs:us-west-1:334824919609:task-definition/ecsworkshopnodejsTaskDef2754560E:1
    logging:
      driver: awslogs
      options:
        awslogs-group: ecsworkshop-nodejs-TaskDefNodeServiceContainerDefLogGroup7CC90673-QxLvkpVQaniw
        awslogs-region: us-west-1
        awslogs-stream-prefix: ecsworkshop-nodejs
    networks:
      ecs-local-network: null
    ports:
    - target: 3000
      published: 4000
      protocol: tcp
networks:
  ecs-local-network:
    external: true
